AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ServiceName:
    Type: String
    Default: 'data-gateway-service'

Resources:
  ### Roles ###
  LoggingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', ['{{resolve:ssm:project-name:1}}', !Sub '${ServiceName}-logging-role']]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs